### ISSUE TITLE
Q: AMQP Driver

### ISSUE THREAD

**Issue by basz** [juriansluiman/SlmQueueAmq#13]
Hoi Jurian,

Are you aware of this package : https://github.com/prolic/HumusAmqp/tree/master/src/Driver A nice PHP7 abstraction of php-amqplib and ext-amqp

Would you be interested in using that in SlmQueueAmq instead of the stomp library you are currently using? I could do some work on that...

It might be the stomp library does something unique (move it to humus..?!) or that you gave up on PHP altogether.

best
Bas

**Comment by boesing** [comment]
Since this package supports PHP5, there is no way to implement PHP7-only code until PHP5 support is dropped.

**Comment by basz** [comment]
I would accept php7 only pull requests for a 2.0
